### ISSUE TITLE
about   vq_dim  and bpv

### ISSUE THREAD

**Issue by xuchen-dev** [Qualcomm-AI-research/gptvq#2]
![image](https://github.com/user-attachments/assets/46cd831d-b3af-42d4-bba5-9f6513e58045)
I find when  vq_dim = 2   the weight bit is double， and the number of cluster centers will grow exponentially, why is their BPV consistent in the paper？Did I miss something?
![image](https://github.com/user-attachments/assets/1bb2051a-d863-4a6d-b90c-fdf03107af5c)

**Comment by akuzmin-qc** [comment]
Thank you for your question. The number of clusters is chosen in such a way that BPV is consistent. For example for 1D VQ, a codebook of 16 cluster centers can be addressed using 4 bits index. While for 2d VQ, if we use 256 cluster centers, it needs an 8-bit index which is exactly 4 bits per weight, same as in the one-dimensional case.
